### PR TITLE
add themeswitch in blog theme

### LINKED ISSUE #115: Dark Mode for blog theme
Would it be possible, to add the dark mode button to the blog theme?

_Loving the project so far, huge thanks :)_

### PR DESCRIPTION
**Pull request by Djiit**
Closes #115

### CODE REVIEW

**Comment by Djiit** [comment]
Hey, this is a very naive implementation so I can get used to the packages and contrib workflow.

I'm clearly not a designer, so I'll need some help on defining some basic but solid variables for the blog "dark theme". In the last commit, I suggested some changes + extracted some `.dark` classes from the `docs` theme.

Happy to discuss all of this! Cheers ;)

**Comment by LucaNerlich** [comment]
well, that was quick :) A bit unfortunate, that the vercel / gitlab preview integration points to the site theme in this case.
But keep up the good work 💪

**Comment by shuding** [comment]
The new `@tailwindcss/typography` or `tailwindcss` is causing issue for me locally:

image

Seems all `prose` styles are missing.

**Comment by B2o5T** [comment]
Closing as completed https://github.com/shuding/nextra/pull/242

**Pull request closed without merging**
