### PR TITLE
fix(search): add fallback bg-color for search result

### PR DESCRIPTION
**Pull request by neighborhood999**
### Firefox

| Light | Dark |
| ------ | ----- |
|Screenshot 2022-02-17 at 14-10-30 React Hooks for Data Fetching – SWR|Screenshot 2022-02-17 at 14-10-15 React Hooks for Data Fetching – SWR|

### Safari

| Light | Dark |
| ------ | ----- |
|截圖 2022-02-17 下午2 09 29|截圖 2022-02-17 下午2 09 40|

## Description

Hi @shuding, thank you for creating an amazing static site generator.

I found a little style issue on the search result and try to fix it, not sure change is good or not, feel free to give me any suggestions, thank you.

Signed-off-by: Jie Peng <im@jiepeng.me>

### CODE REVIEW

**Comment by shuding** [comment]
Thanks for your PR! But it does show the opacity and backdrop blur for me… maybe we should have a way to fallback.

**Comment by shuding** [comment]
For example using something like https://stackoverflow.com/questions/38145368/css-workaround-to-backdrop-filter

**Comment by neighborhood999** [comment]
I use Firefox as the main browser and now I understand it still does not support `backdrop-fitler`...
Let me take the time to figure out any solution, I'm not familiar with Tailwind CSS haha.

**Comment by neighborhood999** [comment]
Hi @shuding:

I added *Firefox* and *Safari* browser comparison screenshots, it works for me, anything needs to adjust feel free to let me know, thank you.

**Comment by shuding** [comment]
Thank you @neighborhood999 and sorry for the delay! The fix looks great to me now 👍

**Pull request merged**
