### PR TITLE
ci: pnpm cache

### PR DESCRIPTION
**Pull request by promer94**
Screen Shot 2022-07-25 at 06 18 21

### CODE REVIEW

**Comment by B2o5T** [comment]
it worked before, also when I configured test action I took configuration mentioned in pnpm website
1241D6F1-32C4-414E-85E1-AC4D53AF1A1A

**Comment by B2o5T** [comment]
Also you specified redundant node js installation, it’s no need look here
5BC34CAC-6DA3-48A8-B4B6-73A0DCC39F1E

**Comment by B2o5T** [comment]
Cc @promer94

**Comment by promer94** [comment]
> it worked before, also when I configured test action I took configuration mentioned in pnpm website 1241D6F1-32C4-414E-85E1-AC4D53AF1A1A

You are right. It did work before.   🤔

I use the configuration from https://github.com/pnpm/action-setup and we also use it swr. 

I will look into this later.

**Pull request merged**
