### PR TITLE
change(blog): improve tags styling

### PR DESCRIPTION
**Pull request by numToStr**
I tried to improve tags' styling; specially in dark-mode where the contrast was very low. Let me know what do you all think :)

### Before

https://user-images.githubusercontent.com/24727447/183091115-7a188744-d1b4-42e3-a752-9e3563bbdc89.mp4

### After

https://user-images.githubusercontent.com/24727447/183091149-dea48d27-2289-4cce-bf73-ec687907ce62.mp4

---

Supersedes #504

### CODE REVIEW

**Comment by B2o5T** [comment]
I guess @numToStr is right, it's better to change bg color rather than color.
Just one notice in hover effect color text should be more contrasted also

**Comment by numToStr** [comment]
@B2o5T I guess you are talking about talking about adjusting text color in light mode?

**Comment by B2o5T** [comment]
yes

**Comment by numToStr** [comment]
@B2o5T I made some adjustment to text color and IMO it looks better.

https://user-images.githubusercontent.com/24727447/183667307-bc6f5d5f-49f2-4552-bff0-fc5d5e6ea99b.mp4

**Comment by numToStr** [comment]
@B2o5T friendly ping :)

**Comment by B2o5T** [comment]
adjusted a little bit and added `not-prose` class to omit adding `!important` in classes

https://user-images.githubusercontent.com/7361780/184086865-f7837270-ab04-4084-8885-fe0e442fc4ac.mov

**Review by B2o5T — APPROVED** [review]

**Comment by numToStr** [comment]
LGTM

**Comment by shuding** [comment]
Thank you @numToStr!

**Pull request merged**
