### PR TITLE
[v3] Add rust icon for codeblocks

### PR DESCRIPTION
**Pull request by hariria**
Adding the official rust icon for codeblocks from https://www.rust-lang.org/logos/rust-logo-blk.svg

### CODE REVIEW

**Review by dimaMachina — APPROVED** [review]

**Comment by hariria** [comment]
@dimaMachina is there anything else needed to merge this in?

**Comment by hariria** [comment]
Cc @shuding

**Comment by hariria** [comment]
@dimaMachina wanted to circle back on this. Any reason why we can't merge it in?

**Comment by dimaMachina** [comment]
will be merged in next release

**Comment by hariria** [comment]
Hey, seems like this may have been forgotten in the recent v3 release?

**Comment by dimaMachina** [comment]
just saw the case on dark mode, I will fix and release 
image

**Pull request merged**
