### PR TITLE
fix missing border in navbar

### PR DESCRIPTION
**Pull request by B2o5T**
@shuding on a dark theme we no longer need a border?

as border is missing on latest preview 
image

### CODE REVIEW

**Comment by shuding** [comment]
Ah @B2o5T I intentionally changed that to be not inset, to show the box shadow on top of the underlying content. For example `inset`:

CleanShot 2022-12-11 at 20 30 20@2x

Without `inset` (looks much better):

CleanShot 2022-12-11 at 20 30 43@2x

**Comment by B2o5T** [comment]
@shuding did you take a look at dark mode? Because in light mode there is a border and in dark - not

**Comment by shuding** [comment]
I'm fixing it now on this PR!

**Comment by B2o5T** [comment]
Thanks 🙏❤️

**Pull request merged**
