### PR TITLE
split css to `hamburger`/`scrollbar`/`typesetting-article` css files

### PR DESCRIPTION
**Pull request by B2o5T**
review only first commit

### CODE REVIEW

**Comment by B2o5T** [comment]
@shuding `swr-site` build locally passes, seems like ci glitch?

**Comment by shuding** [comment]
It looks like a build error though:

```

TypeError: Cannot read properties of null (reading 'useContext')
00:24:23	    at Object.exports.useContext (/vercel/path0/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.production.min.js:24:118)
00:24:23	    at useRouter (/vercel/path0/node_modules/.pnpm/next@12.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/router.js:120:27)
00:24:23	    at Layout (/vercel/path0/examples/swr-site/.next/server/chunks/5252.js:2866:42)
00:24:23	    at Module.4489 (/vercel/path0/examples/swr-site/.next/server/pages/about/a-page.en-US.js:574:137)
00:24:23	    at __webpack_require__ (/vercel/path0/examples/swr-site/.next/server/webpack-runtime.js:25:43)
00:24:23	    at __webpack_exec__ (/vercel/path0/examples/swr-site/.next/server/pages/about/a-page.en-US.js:826:39)
00:24:23	    at /vercel/path0/examples/swr-site/.next/server/pages/about/a-page.en-US.js:827:77
00:24:23	    at Function.__webpack_require__.X (/vercel/path0/examples/swr-site/.next/server/webpack-runtime.js:120:21)
00:24:23	    at /vercel/path0/examples/swr-site/.next/server/pages/about/a-page.en-US.js:827:47
00:24:23	    at Object.<anonymous> (/vercel/path0/examples/swr-site/.next/server/pages/about/a-page.en-US.js:830:3)
00:24:23	
00:24:23	> Build error occurred
00:24:23	Error: Failed to collect page data for /about/a-page.en-US
00:24:23	    at /vercel/path0/node_modules/.pnpm/next@12.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/utils.js:644:15
00:24:23	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
00:24:23	  type: 'Error'
00:24:23	}
```

(I'll try to make the preview project public so everyone can see it!)

**Comment by B2o5T** [comment]
@shuding fixed, this was a glitch, but after merge another PR there was a real issue :)

**Comment by shuding** [comment]
Thanks!

**Pull request merged**
