### PR TITLE
[v3] Playground Component

### PR DESCRIPTION
**Pull request by hariria**
fixes https://github.com/shuding/nextra/issues/2543 https://github.com/shuding/nextra/issues/1167

This PR introduces a `<Playground />` component and `compileMdxClient` function for individuals to render MDX purely on the client. It emulates much of the same functionality as `compileMdx`, but removes any server related dependencies like `node:path`. There are a variety of use-cases this may be helpful for. 

- [x] Demo-ing Nextra's renderer / having a place where MDX can be rendered in a playground environment
- [x] Substitute for RemoteContent rendering in situations where sidebar / static generation is not needed

Inspired largely by the [MDX Playground here](https://mdxjs.com/playground/).

### CODE REVIEW

**Comment by dimaMachina** [comment]
Hi, thank you for sponsoring, I am busy currently with my full time work and upcoming graphql conf 2024, I will review your PR once I will have some free time

**Comment by hariria** [comment]
Awesome appreciate it @dimaMachina. Totally understand, looking forward to your thoughts!

**Comment by dimaMachina** [comment]
@hariria can you click on checkbox to allow me pushing on your branch? 
image

**Comment by dimaMachina** [comment]
1. I removed `compileMdxClient.ts` since it repeats a lot of code from `server/compile.ts`
2. I fixed `compileMdx` to be platform agnostic, so now it can be imported in the browser and code be compiled too (I needed to fix our remark mermaid plugin https://github.com/the-guild-org/docs/pull/1640)
3. moved your doc page from `examples/docs` to nextra.site docs
4. added true playground with live editor and preview

https://github.com/user-attachments/assets/5124b7b9-b4f6-4403-9846-476a1b7bbc4d

once you change PR rights, I will push my changes and will release new alpha version

**Comment by hariria** [comment]
Wow this looks incredible @dimaMachina ! Thanks so much for the hard work on this. I think people are really going to love it. Addressing your comments from before:

1. I don't see an option to enable maintainers to edit on my side for some reason as seen in the screenshot below. I tried looking into this on the [Github Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) as well but wasn't able to figure out how to change it. I think it may be because the fork is on an organization's account, not a user. Worst case scenario maybe we can merge it in and put your commits on top of the changes or I can make a new fork that's on my personal account. Lmk which one works best.
2. Is there any chance we could add a prop to the `Playground` component to make it `preview only` if desired?

Screenshot 2024-08-31 at 8 07 18 AM
Screenshot 2024-08-31 at 8 17 36 AM

**Comment by dimaMachina** [comment]
@hariria I created https://github.com/shuding/nextra/pull/3174 to make it easy, I will close this PR

> Is there any chance we could add a prop to the Playground component to make it preview only if desired?

it will depend on your component who change raw mdx, either[ html element with content editable](https://github.com/shuding/nextra/blob/playground-client/docs/pages/docs/guide/advanced/playground.mdx?plain=1) or [textarea](https://github.com/shuding/nextra/blob/9579d059ea05cb2e3091f17fe7f40dadd41f8829/docs/pages/docs/guide/advanced/playground.mdx?plain=1#L51-L59) with onChange handler

**Comment by hariria** [comment]
Got it the implementation makes sense. Thanks!

**Pull request closed without merging**
