### PR TITLE
allow hide sidebar, add new option `sidebar.toggleButton?: boolean = false`

### PR DESCRIPTION
**Pull request by B2o5T**
fixes 2 years ago issue :) https://github.com/shuding/nextra/issues/67

### CODE REVIEW

**Comment by shuding** [comment]
Incredible, thank you!

**Comment by B2o5T** [comment]
@shuding thanks! Just saw small issues on mobile, will mark is as ready when it’s will be done

**Comment by C-EO** [comment]
@B2o5T When is this PR going to be finished? I'm in dire need of this feature.

**Comment by B2o5T** [comment]
@C-EO need to make a huge rebase  🙈

**Pull request merged**
