### PR TITLE
fix: remove trailing slash

### PR DESCRIPTION
**Pull request by niikeec**
This PR resolves issue #1425.

### CODE REVIEW

**Review by B2o5T — CHANGES_REQUESTED** [review]
Nice! Can you add some test to ensure this will be not broken in the future, example of tests for this function are here https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/__test__/use-fs-route.spec.ts

**Comment by niikeec** [comment]
Pushed a test

**Review by B2o5T — APPROVED** [review]
Thank you!

**Comment by niikeec** [comment]
No problem

**Pull request merged**
