### PR TITLE
[wip v3]: new i18n, remove `_app.mdx`, remove `newNextLinkBehavior`

### PR DESCRIPTION
**Pull request by B2o5T**
- ❌ remove `_app.mdx`, use `_app.{js,jsx}` or `_app.{ts,tsx}` for TypeScript projects instead

- ❌ remove Nextra middleware `nextra/locales`

- ❌ remove `parseFileName` from `nextra/utils`

- ❌ remove `nextra/filter-route-locale`

- ❌ remove `resolvePageMap` and `pageMapCache` from `nextra/page-map`

- ❌ remove `__nextraPageOptions.pageNextRoute`

- ❌ remove `pageOpts.route` and `pageOpts.newNextLinkBehavior`

- ❌ remove `LoaderOptions.defaultLocale`

- ❌ remove `__nextra_internal__.context[route].themeConfig`

- ✅ add `nextra/fetch-filepaths-from-github`

- save `pageMap` to `.next/static/chunks/nextra-page-map-{locale}.mjs`

- save `fileMap` to `.next/static/chunks/nextra-file-map.mjs`

tbd, bundle size should not be changed after above

### CODE REVIEW

**Comment by C-EO** [comment]
@B2o5T can't you do dual support instead of deprecating `_app.mdx`? It becomes quite unreliable to keep deprecating new ideas. Almost all the community will be affected.

**Comment by B2o5T** [comment]
@C-EO it’s fine to do breaking changes in major releases

**Comment by AndreyGrek** [comment]
> @B2o5T can't you do dual support instead of deprecating `_app.mdx`? It becomes quite unreliable to keep deprecating new ideas. Almost all the community will be affected.

And on the contrary, I need it, since the current implementation of internalization cannot be used, much less scaled.
I really look forward to the impact of this PR

**Comment by B2o5T** [comment]
@AndreyGrek Yeah, the current i18n is too buggy and should be improved, especially https://github.com/shuding/nextra/issues/712 https://github.com/shuding/nextra/issues/1263 https://github.com/shuding/nextra/issues/1922

and about releasing v3 - I don't have an exact time, I am on vacation, busy with another open source projects, and also will have conferences in the following months

hope to finish all tasks from the roadmap at the end of this year 🤞

**Pull request merged**
