### PR TITLE
Fix #283: Use util.promisify to wrap graceful-fs methods in nextra loader.js

### LINKED ISSUE #283: core branch: EMFILE too many open files error on Mac build
On the core branch, if you build `example/docs` with sufficient content (I copied `about.en.md` to `about1.en.md`, `about2.en.md`, ... `about39.en.md`), you run into `UnhandledPromiseRejectionWarning` errors: `EMFILE: too many open files`

This appears to be related to the `Promise.all` approach of `getPageMap/getFiles` in `packages/nextra/src/loader.js`. Making that operation synchronous (I tweaked the code with a synchronous version of `getPageMap`) allows the Mac build to succeed.

This open files build error seems limited to my Mac builds. My Linux/Ubuntu builds don't run into this.

I'm running macOS Big Sur version 11.6 on a 2019 MacBook Pro Intel Core i7 with 32 GB memory.

```
$ next build
You have i18n enabled for Nextra.
info  - Checking validity of types  
warn  - No ESLint configuration detected. Run next lint to begin setup
(node:5683) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, open '/Users/robbear/dev/robbear/nextra/examples/docs/pages/nextra/about2.en.md'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5683) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, open '/Users/robbear/dev/robbear/nextra/examples/docs/pages/blog/hello-world.en.md'
(node:5683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

### PR DESCRIPTION
**Pull request by robbear**
Fixes #283 

The `graceful-fs` module:

> Queues up open and readdir calls, and retries them once something closes if there is an EMFILE error from too many file descriptors. (https://github.com/isaacs/node-graceful-fs#readme)

Issue #283 is demonstrating that this is not happening, suggesting the current method for calling promise-based methods on the `graceful-fs` module is not correct. Instead, wrapping `graceful-fs`'s methods with `promisify` from the `util` module results in a successful Mac build against a docs site with many markdown files. 

This solution can probably also be tested against the `shu/67f5` branch's `swr-site` documentation project on a Mac as well. That project currently fails to build on my Mac.

### CODE REVIEW

**Comment by shuding** [comment]
Thank you so much Rob, I'll take a careful look and do a test to ensure the issue is gone.

**Comment by shuding** [comment]
There're some conflicts — could you resolve them so we can get this merged? Thanks!

**Comment by robbear** [comment]
It looks like I can resolve the conflicts (push coming soon), but my tests show with the merge of `shu/67f5` into `core`, there may be new Mac build issues introduced. I'll update the status in a subsequent comment.

**Comment by robbear** [comment]
@shuding I'm not able to get `swr-site` to build on a Mac with this PR. I see `EMFILE` errors in opening `shiki` language json files, for instance. Everything builds and runs on Linux.

I've been taking snap shots of the `core` branch and applying them to my own site work, similar to `swr-site` with a key exception of dropping the `pages/_middleware.js` file (no locale support in my site). With the changes illustrated in this PR to wrap `fs` calls with `utils.promisify`, my site builds on Mac and Linux. 

I'm stumped about Mac builds of `swr-site`.

**Comment by shuding** [comment]
Thanks for the context @robbear, I'll test this with `swr-site` on my machine!

**Comment by shuding** [comment]
But that might be another issue and I'll take a look separately. This fix looks great regardless, thank you!

**Pull request merged**
