### PR TITLE
add `nextraConfig.unstable_readingTime` option for blog theme

### PR DESCRIPTION
**Pull request by B2o5T**
fixes https://github.com/shuding/nextra/issues/683

## disabled
image
## enabled
image
## another example
image

### CODE REVIEW

**Comment by numToStr** [comment]
@B2o5T Excellent work 🎉. May I ask you Is there is reason for putting the tags on next line? Isn't it possible to just inline the reading time between date and tags?

**Comment by B2o5T** [comment]
didn't want to put too many things on one line, let's wait for the thought of @shuding

**Comment by shuding** [comment]
Great feature, thanks @B2o5T!

When there're many tags it looks cleaner to break into a new line indeed. BTW can we make them top-aligned?

CleanShot 2022-08-11 at 23 21 01

**Comment by numToStr** [comment]
Yes, I also agree. Moving tags on the next line only when there are many tags and aligning back-button and theme-switch with date will also work.

**Comment by B2o5T** [comment]
@shuding rebased and fixed vertical alignment, what about adding the same in docs theme? which place will be the best to put it there?

**Comment by shuding** [comment]
Not sure if we want to put this on the docs theme (maybe as an option that defaults to false) because usually when people look at docs, they only check the section that they need (hence https://tailwindcss.com uses the search bar as CTA), unlike blogs.

**Comment by shuding** [comment]
We can ship this first and have a discussion about that feature in docs!

**Review by shuding — APPROVED** [review]

**Pull request merged**
