### PR TITLE
feat: add more social icon

### PR DESCRIPTION
**Pull request by ikhsangama**
add more some common social media icon

### CODE REVIEW

**Comment by Netail** [comment]
Facebook & Twitter in that case maybe too?

**Comment by glmn** [comment]
Telegram 🙏

**Comment by Netail** [comment]
> > Facebook, Twitter, Whatsapp, Threads in that case maybe too?
> 
> @Netail isn't Twitter icon already reserved here as 'X'? Do we need legacy logo?

Woops, you're right hahaha. Still didn't got used to it being called X now

**Comment by Netail** [comment]
Terima kasih 🙏

**Comment by dimaMachina** [comment]
thanks, but I don't think I would like to merge it, I would like to keep icons minimal and would suggest you to use icons library or copy-paste needed icons directly for your project

**Pull request closed without merging**
