### PR TITLE
Strip file extension from URL route

### PR DESCRIPTION
**Pull request by zburk**
When exporting to static HTML files, the active route in the sidebar does not highlight correctly since it detected route in `useFSRoute` includes the file extension.

Original Behavior:
Detected route - `get-started.html`
Screenshot 2023-06-07 at 9 14 08 AM

New Behavior:
Detected route - `get-started`
Screenshot 2023-06-07 at 9 13 00 AM

### CODE REVIEW

**Comment by B2o5T** [comment]
could you add tests too for your case? https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/__test__/use-fs-route.spec.ts

**Comment by zburk** [comment]
Done. However, when I try to run the tests I get an error:
```
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
```

Are you able to successfully run the tests or is something configured incorrectly on my computer?

**Comment by B2o5T** [comment]
> Are you able to successfully run the tests or is something configured incorrectly on my computer?

something was broken in newly next.js update 🥲 need to find a way how to test `next/router` now 😞

**Review by B2o5T — APPROVED** [review]
ty, sorry it taken some time to merge this pr

**Pull request merged**
