### PR TITLE
fix for MDXProvider/TOC, and bump mdx version to 2.0.0-rc2 

### PR DESCRIPTION
**Pull request by ChinW**
- fix MDXProvider 
- fix TOC 
- bump @mdx-js/react and @mdx-js/loader

ref: https://github.com/mdx-js/mdx/issues/1831

### CODE REVIEW

**Comment by shuding** [comment]
Thank you so much for this, I’ll take a look tomorrow!

**Comment by ChinW** [comment]
thanks for making this great tool! :D

**Review by kanadgupta — CHANGES_REQUESTED** [review]
Hi @ChinW thank you so much for this! I noticed that code highlighting wasn't working in the blog theme and I believe it's related to the mismatching MDX versions that you're addressing in this PR. Would you also be willing to bump the `@mdx-js/react` version in the blog subpackage as well?
https://github.com/shuding/nextra/blob/223c78c2500a8d0c7aa4aa6967840d6da7e647b6/packages/nextra-theme-blog/package.json#L24

I'm not sure what (if any) context provider changes are required (like you've done with the docs theme), but I was able to get code highlighting working in the blog theme again by simply bumping `@mdx-js/react` to `2.0.0-rc.2` in my `nextra-theme-blog` dependency. Happy to open a PR with this if needed—thanks again!

**Comment by ChinW** [comment]
@kanadgupta for sure, just updated

**Comment by shuding** [comment]
Thank you so much @ChinW @kanadgupta!

**Comment by ChinW** [comment]
thanks @shuding again! just for check, seems the npm version hasn't been updated

**Pull request merged**
