### PR TITLE
[Blog/Docs] Add copy to clipboard button for code-blocks.

### PR DESCRIPTION
**Pull request by B2o5T**
- [x] Add `NextraConfig.unstable_defaultShowCopyCode` option to show button by default
- [x] add `copy` and `copy=false` options for code-blocks

fixes https://github.com/shuding/nextra/issues/539

maybe rename `unstable_defaultShowCopyCode` to `unstable_defaultShowCopyButton` ?

### CODE REVIEW

**Comment by numToStr** [comment]
@B2o5T Wonderful! Thanks for working on this. 

How about `unstable_copyCode`? the `boolean` value already implies show/hide and default/not-default. So, it's better to just omit that. We can also document this in jsdoc.

**Comment by B2o5T** [comment]
Since we have `defaultMenuCollapsed` option, I wanted also be more explicit in naming of property to not lost context of default showing/hiding option of copy button

**Comment by numToStr** [comment]
that's why suggested to document the behavior in jsdoc instead.

**Comment by B2o5T** [comment]
Yeah, also we need setup some generated documentation for nextra config and theme config options

**Comment by shuding** [comment]
Great work!

**Comment by numToStr** [comment]
@B2o5T Sorry for the noise but the latest beta release doesn't have this change. Is that a mistake? And It seems that `better-loader-types` (to which this PR got merged) is also missing.

**Comment by B2o5T** [comment]
@numToStr this PR has conflicts that must be resolved https://github.com/shuding/nextra/pull/718

**Pull request merged**
